// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GlinerTokenizer>>
abstract class GlinerTokenizer implements RustOpaqueInterface {
  /// Encode `text` to token IDs (no special tokens — GLiNER adds its own).
  Uint32List encode({required String text});

  /// Load a tokenizer from a `tokenizer.json` file path (on-device path).
  static GlinerTokenizer load({required String tokenizerJsonPath}) =>
      RustLib.instance.api.crateApiTokenizerGlinerTokenizerLoad(
        tokenizerJsonPath: tokenizerJsonPath,
      );
}
